# 生产环境
server:
  port: 8090

spring:
  datasource:  #数据源相关的配置节点
    username: root
    password: hc2919
    url: jdbc:mysql://localhost:3306/db_chatter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver #mysql / MariaDB 驱动

    type: com.zaxxer.hikari.HikariDataSource   #  第一种数据源 Hikari   === 开始
    hikari:
      connection-timeout: 30000   #等待连接池分配连接的最大时长（毫秒）,超过这个时长还没可用的连接则发生SQLException,默认30秒
      minimum-idle: 5       #最小连接数
      maximum-pool-size: 20   #最大连接数
      auto-commit: true       #自动提交
      idle-timeout: 6000000   #连接超时的最大时长（毫秒），超时则被释放（retired）,默认：10分钟
      pool-name: DateSourceHikariCP #连接池名字
      max-lifetime: 1800000         #连接的生命时长（毫秒）超时而且没被使用则被释放（retired）,默认：30分钟 1800000ms
      connection-test-query: SELECT 1  # 第一种数据源 Hikari   === 结束
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: hc2919
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
#mybatis 相关配置
mybatis:
  mapper-locations: classpath*:cn/peyton/plum/**/mapper/*.xml  #所有 mapper 映射的文件所在目录位置
  type-aliases-package: cn.peyton.plum.community.pojo    #所有数据库表逆向后所--映射的实体类 Entity/Bean/POJO

pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
