#
spring:
  profiles:
    active: dev   #切换运行环境
  messages:
    basename: i18n.doc  #国际化
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/  #前缀
    suffix: .html  #后缀
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    hiddenmethod:
      filter:
        enabled: true #设置开启RESTFul风格
  servlet:
    multipart:
      max-file-size: 500KB #设置文件上传大小的限制
      max-request-size: 2MB #文件最大请求限制，用于批量


